CREATE TABLE IF NOT EXISTS app_layout (
  id INT PRIMARY KEY DEFAULT 1,
  layout_mode VARCHAR(10) NOT NULL DEFAULT 'classic',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
